In [ ]:
from array import *


In [ ]:
from array import *

# val = array('i', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# # print(val)
# # print(val[0])
# # print(val[1])
# # print(val[2])
# # print(val[3])
# # print(val[4])
# # print("\n")

# # for i in range(0,5): 
# #     print(val[i], end=" ")
# # print("\n")
# # # 1 2 3 4 5 because we gave the range of 0 to 5, so it will print the value of index 0 to 4

# # for i in val:
# #     print(i, end=", ")
# # print("\n")
# # # 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 because we are iterating through the array and printing each value

# # for i in range(0, len(val)): 
# #     print(val[i], end=" ")
# # print("\n")
# # # 1 2 3 4 5 6 7 8 9 10 because we are giving the range of 0 to the length of the array, so it will print all the values in the array
# # print(val.typecode) # this will print the type code of the array, which is 'd' for double
# # # val.reverse() # this will reverse the array
# # # for i in range(0, len(val)): 
# # #     print(val[i], end=" ")
# # # print("\n")

# # val.insert(1, 50) # this will insert the value 50 at index 1
# # val.append(100) # this will append the value 100 at the end of the array
# # val[2] = 200 # this will change the value at index 2 to 200
# # val.pop(3) # this will remove the value at index 3
# # val.remove(5) # this will remove the first occurrence of the value 5 in the array
# for i in range(0, len(val)): 
#     print(val[i], end=" ")
# print("\n")

# # abc = val[1:5] # this will create a new array 'abc' which will contain the values from index 1 to 4 of the original array 'val'
# # abc = val[2: -3] # this will create a new array 'abc' which will contain the values from index 2 to the second last index of the original array 'val'
# abc = val[::-1] # this will create a new array 'abc' which will contain the values of the original array 'val' in reverse order
# for i in range(0, len(abc)): 
#     print(abc[i], end=" ")

# # copyarray = array(val.typecode, (x for x in val)) # this will create a copy of the array using a 'generator expression'
# # # (x for x in val) which iterates through each element in the original array 'val' and yields it one at a time to the new array 'copyarray'. The type code of the new array is the same as the original array, which is 'd' for double.)
# # copyarray = array(val.typecode, (x*2 for x in val))
# # for i in range(0, len(copyarray)): 
# #     print(copyarray[i], end=" ")

arr = array('i',[])
n = int(input("Enter the number of elements you want to add in the array: "))
for i in range(0,n):
    arr.append(int(input("Enter the element: ")))

for x in arr:
    print(x, end=" ")

In [ ]:
from array import *

val = array('d', [1, 2, 3, 4, 5, 6, 7, 8, 9.5, 10])
# print(val)

for i in range(0, len(val)): 
    print(val[i], end=" ")
print("\n")
# 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.5 10.0 we used 'd' as the type code for double, so all the values are printed as floating point numbers.
# If we had used 'i' as the type code for integer, 'float' object cannot be interpreted as an integer because we cannot store a floating point number in an array of integers.


In [ ]:
from array import *

val = array('u', ['a', 'b', 'c', 'd', 'e'] )
print(val)
for i in range(0, len(val)): 
    print(val[i], end=" ")

In [4]:
arr = array('i',[12,46,78,90,34,56,89,23,45,67])

i = arr.index(78) # this will return the index of the first occurrence of the value 78 in the array
print(i) # this will print the index of the value 78 in the array, which is 2


2


array using numpy

In [ ]:
import numpy as np # we are importing the numpy library and giving it an alias 'np' so that we can use it in our code without having to type 'numpy' every time.
from numpy import * # this will import all the functions and classes from the numpy library so that we can use them in our code without having to type 'np' every time.
# numpy is used to create hetrogeneous arrays, which can contain elements of different data types, whereas the array module in Python can only create homogeneous arrays, which can only contain elements of the same data type.
# val = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# val = array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], float) # this will create an array of floating point numbers because we have specified the data type as float. 
# val = linspace(10,20,5) # this will create an array of 5 equally spaced values between 10 and 20, which are 10.0, 12.5, 15.0, 17.5, and 20.0 here 10 is included because the linspace function generates values starting from the start value, and 20 is included because the linspace function generates values up to and including the stop value.
# val = arange(10, 20, 2) # this will create an array of values starting from 10 to 20 with a step of 2, which are 10, 12, 14, 16, and 18 ,here 20 is not included because the arange function generates values up to, but not including, the stop value.
# val = logspace(10, 20, 5) # this will create an array of 5 logarithmically spaced values between 10 and 20, which are 10000.0, 46415.88833612778, 215443.4690031883, 999999.9999999998, and 10000000.0
# val = zeros(5) # this will create an array of 5 zeros, which are 0.0, 0.0, 0.0, 0.0, and 0.0
# val = ones(5) # this will create an array of 5 ones, which are 1.0, 1.0, 1.0, 1.0, and 1.0
# val = full(7, 5) # this will create an array of 7 elements, all with the value 5
# for x in val:
#     print(x, end=" ")


#types of arrays in numpy
# 1. zero dimensional array (scalar)

zero = array(5) # this will create a zero dimensional array (scalar) with the value 5
print(zero) # this will print the value of the zero dimensional array, which is 5
print("\n")
# 2. one dimensional array (vector)

one = array([1, 2, 3, 4, 5]) # this will create a one dimensional array (vector) with the values 1, 2, 3, 4, and 5
print(one) # this will print the values of the one dimensional array, which are 1, 2, 3, 4, and 5
print("\n")
# 3. two dimensional array (matrix)

two = array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # this will create a two dimensional array (matrix) with the values 1, 2, 3 in the first row, 4, 5, 6 in the second row, and 7, 8, 9 in the third row
print(two) # this will print the values of the two dimensional array, which are 1, 2, 3 in the first row, 4, 5, 6 in the second row, and 7, 8, 9 in the third row_stack 
print("\n")
# 4. three dimensional array (tensor)

three = array([[[1, 2], [3, 4]], [[16, 17], [19, 20,]]]) # this will create a three dimensional array (tensor) with the values 1 to 24 arranged in three layers of three rows and three columns each
print(three) # this will print the values of the three dimensional array, which are 1 to 24 arranged in three layers of three rows and three columns each

5
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[[ 1  2]
  [ 3  4]]

 [[16 17]
  [19 20]]]


In [ ]:
#reverse a number 
class Solution(object):
    def reverse(self, x):
        x = int(input("Enter a number: "))
        rev = 0
        for i in str(x):
            digit = x % 10
            rev = rev * 10 + digit
            x = x // 10
        print("Reversed number is: ", rev)

: 